// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBcg5VOA608NEf3r9s8QLb7aA5z7K8DuM',
    appId: '1:326120873688:web:d14697a63954798f7e01ad',
    messagingSenderId: '326120873688',
    projectId: 'immo-lmd',
    authDomain: 'immo-lmd.firebaseapp.com',
    storageBucket: 'immo-lmd.firebasestorage.app',
    measurementId: 'G-S2BWSCKS2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2m4Cgp5WcjghgLd5RTkosdqT-qpFCSXM',
    appId: '1:326120873688:android:454f8a10366b812c7e01ad',
    messagingSenderId: '326120873688',
    projectId: 'immo-lmd',
    storageBucket: 'immo-lmd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZIuyIVjaCX0pas613-SNot8BoO-IP-Y',
    appId: '1:326120873688:ios:de0d271aab9479ca7e01ad',
    messagingSenderId: '326120873688',
    projectId: 'immo-lmd',
    storageBucket: 'immo-lmd.firebasestorage.app',
    iosClientId: '326120873688-n0vvvengf3klhptbefb9ushepgtv37rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZIuyIVjaCX0pas613-SNot8BoO-IP-Y',
    appId: '1:326120873688:ios:de0d271aab9479ca7e01ad',
    messagingSenderId: '326120873688',
    projectId: 'immo-lmd',
    storageBucket: 'immo-lmd.firebasestorage.app',
    iosClientId: '326120873688-n0vvvengf3klhptbefb9ushepgtv37rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBcg5VOA608NEf3r9s8QLb7aA5z7K8DuM',
    appId: '1:326120873688:web:72f331f458de8f427e01ad',
    messagingSenderId: '326120873688',
    projectId: 'immo-lmd',
    authDomain: 'immo-lmd.firebaseapp.com',
    storageBucket: 'immo-lmd.firebasestorage.app',
    measurementId: 'G-2DQJRJRVZ1',
  );
}
